### ISSUE TITLE
Test distribution-packages fails on ubuntu due to missing APT handling

### ISSUE THREAD

**Issue by dviererbe** [canonical/dotnet-regular-tests#2]
```
Traceback (most recent call last):
  File "/home/dviererbe/Repositories/dotnet/dotnet-regular-tests/distribution-packages/./test-standard-packages", line 482, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dviererbe/Repositories/dotnet/dotnet-regular-tests/distribution-packages/./test-standard-packages", line 318, in main
    okay = check_packages(package_source, package_prefix, runtime_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dviererbe/Repositories/dotnet/dotnet-regular-tests/distribution-packages/./test-standard-packages", line 369, in check_packages
    package = package_source.find_package(package_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dviererbe/Repositories/dotnet/dotnet-regular-tests/distribution-packages/./test-standard-packages", line 228, in find_package
    return self._rpm_query(name, [])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dviererbe/Repositories/dotnet/dotnet-regular-tests/distribution-packages/./test-standard-packages", line 241, in _rpm_query
    completed = subprocess.run(['rpm', '-q', *query_args, package_name],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'rpm'
Process Exit Code: 1
```

**Comment by dviererbe** [comment]
Skipping test on Ubuntu the meantime.
